# Generated by Django 5.2.6 on 2025-09-28 22:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del empleado', max_length=100)),
                ('apellido', models.CharField(help_text='Apellido del empleado', max_length=100)),
                ('puesto', models.CharField(blank=True, help_text='Cargo o puesto del empleado', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, help_text='Correo electrónico (opcional)', max_length=254, null=True, unique=True)),
                ('hora_entrada_supuesta', models.TimeField(help_text='Hora de entrada programada (ej. 09:00:00)')),
                ('hora_salida_supuesta', models.TimeField(help_text='Hora de salida programada (ej. 18:00:00)')),
                ('codigo_qr_unico', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Código único para el QR del empleado. Se genera automáticamente.', unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el empleado está activo en la empresa')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_entrada', models.DateTimeField(help_text='Fecha y hora exactas de la entrada')),
                ('fecha_hora_salida', models.DateTimeField(blank=True, help_text='Fecha y hora exactas de la salida (puede estar vacío)', null=True)),
                ('llego_tarde', models.BooleanField(default=False, help_text='Se marca si el empleado llegó después de su hora supuesta (con tolerancia)')),
                ('notas', models.TextField(blank=True, help_text='Notas u observaciones sobre este registro', null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='bitacora.empleado')),
            ],
        ),
    ]
