# Generated by Django 5.2.6 on 2025-09-28 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutos_tolerancia_entrada', models.PositiveIntegerField(default=10, help_text='Número de minutos de tolerancia para considerar una llegada como puntual.')),
            ],
            options={
                'verbose_name_plural': 'Configuraciones',
            },
        ),
    ]
