# Generated by Django 5.2.6 on 2025-12-14 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0002_configuracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='usa_horario_variable',
            field=models.BooleanField(default=False, help_text='Si se marca, el sistema buscará el horario específico del día de la semana en lugar del general.'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='hora_entrada_supuesta',
            field=models.TimeField(help_text='Hora de entrada programada general (ej. 09:00:00)'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='hora_salida_supuesta',
            field=models.TimeField(help_text='Hora de salida programada general (ej. 18:00:00)'),
        ),
        migrations.CreateModel(
            name='HorarioDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('es_dia_libre', models.BooleanField(default=False, help_text='Marcar si este día el empleado descansa')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_dias', to='bitacora.empleado')),
            ],
            options={
                'ordering': ['dia_semana'],
                'unique_together': {('empleado', 'dia_semana')},
            },
        ),
    ]
